services:
  nginx:
    image: nginx:latest
    container_name: nginx-downloads
    ports:
      - "80:80"
    volumes:
      - ~/Downloads:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped